# coding: utf-8

"""
    Rumble API

    Rumble Network Discovery API  # noqa: E501

    OpenAPI spec version: 2.11.0
    Contact: support@rumble.run
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssetsWithCheckpoint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'since': 'int',
        'assets': 'list[Asset]'
    }

    attribute_map = {
        'since': 'since',
        'assets': 'assets'
    }

    def __init__(self, since:int=None, assets:list[Asset]=None):  # noqa: E501
        """AssetsWithCheckpoint - a model defined in Swagger"""  # noqa: E501
        self._since = None
        self._assets = None
        self.discriminator = None
        self.since = since
        self.assets = assets

    @property
    def since(self):
        """Gets the since of this AssetsWithCheckpoint.  # noqa: E501


        :return: The since of this AssetsWithCheckpoint.  # noqa: E501
        :rtype: int
        """
        return self._since

    @since.setter
    def since(self, since):
        """Sets the since of this AssetsWithCheckpoint.


        :param since: The since of this AssetsWithCheckpoint.  # noqa: E501
        :type: int
        """
        if since is None:
            raise ValueError("Invalid value for `since`, must not be `None`")  # noqa: E501

        self._since = since

    @property
    def assets(self):
        """Gets the assets of this AssetsWithCheckpoint.  # noqa: E501


        :return: The assets of this AssetsWithCheckpoint.  # noqa: E501
        :rtype: list[Asset]
        """
        return self._assets

    @assets.setter
    def assets(self, assets):
        """Sets the assets of this AssetsWithCheckpoint.


        :param assets: The assets of this AssetsWithCheckpoint.  # noqa: E501
        :type: list[Asset]
        """
        if assets is None:
            raise ValueError("Invalid value for `assets`, must not be `None`")  # noqa: E501

        self._assets = assets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            elif value is not None:
                result[attr] = value
        if issubclass(AssetsWithCheckpoint, dict):
            for key, value in self.items():
                if value is not None:
                    result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetsWithCheckpoint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
