# coding: utf-8

"""
    Rumble API

    Rumble Network Discovery API  # noqa: E501

    OpenAPI spec version: 2.11.0
    Contact: support@rumble.run
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AzureClientSecretCredentialFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_id': 'str',
        'client_secret': 'str',
        'tenant_id': 'str',
        'multi_subscription': 'str',
        'subscription_id': 'str'
    }

    attribute_map = {
        'client_id': 'client_id',
        'client_secret': 'client_secret',
        'tenant_id': 'tenant_id',
        'multi_subscription': 'multi_subscription',
        'subscription_id': 'subscription_id'
    }

    def __init__(self, client_id:str=None, client_secret:str=None, tenant_id:str=None, multi_subscription:str=None, subscription_id:str=None):  # noqa: E501
        """AzureClientSecretCredentialFields - a model defined in Swagger"""  # noqa: E501
        self._client_id = None
        self._client_secret = None
        self._tenant_id = None
        self._multi_subscription = None
        self._subscription_id = None
        self.discriminator = None
        self.client_id = client_id
        self.client_secret = client_secret
        self.tenant_id = tenant_id
        if multi_subscription is not None:
            self.multi_subscription = multi_subscription
        if subscription_id is not None:
            self.subscription_id = subscription_id

    @property
    def client_id(self):
        """Gets the client_id of this AzureClientSecretCredentialFields.  # noqa: E501


        :return: The client_id of this AzureClientSecretCredentialFields.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this AzureClientSecretCredentialFields.


        :param client_id: The client_id of this AzureClientSecretCredentialFields.  # noqa: E501
        :type: str
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def client_secret(self):
        """Gets the client_secret of this AzureClientSecretCredentialFields.  # noqa: E501


        :return: The client_secret of this AzureClientSecretCredentialFields.  # noqa: E501
        :rtype: str
        """
        return self._client_secret

    @client_secret.setter
    def client_secret(self, client_secret):
        """Sets the client_secret of this AzureClientSecretCredentialFields.


        :param client_secret: The client_secret of this AzureClientSecretCredentialFields.  # noqa: E501
        :type: str
        """
        if client_secret is None:
            raise ValueError("Invalid value for `client_secret`, must not be `None`")  # noqa: E501

        self._client_secret = client_secret

    @property
    def tenant_id(self):
        """Gets the tenant_id of this AzureClientSecretCredentialFields.  # noqa: E501


        :return: The tenant_id of this AzureClientSecretCredentialFields.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this AzureClientSecretCredentialFields.


        :param tenant_id: The tenant_id of this AzureClientSecretCredentialFields.  # noqa: E501
        :type: str
        """
        if tenant_id is None:
            raise ValueError("Invalid value for `tenant_id`, must not be `None`")  # noqa: E501

        self._tenant_id = tenant_id

    @property
    def multi_subscription(self):
        """Gets the multi_subscription of this AzureClientSecretCredentialFields.  # noqa: E501


        :return: The multi_subscription of this AzureClientSecretCredentialFields.  # noqa: E501
        :rtype: str
        """
        return self._multi_subscription

    @multi_subscription.setter
    def multi_subscription(self, multi_subscription):
        """Sets the multi_subscription of this AzureClientSecretCredentialFields.


        :param multi_subscription: The multi_subscription of this AzureClientSecretCredentialFields.  # noqa: E501
        :type: str
        """

        self._multi_subscription = multi_subscription

    @property
    def subscription_id(self):
        """Gets the subscription_id of this AzureClientSecretCredentialFields.  # noqa: E501


        :return: The subscription_id of this AzureClientSecretCredentialFields.  # noqa: E501
        :rtype: str
        """
        return self._subscription_id

    @subscription_id.setter
    def subscription_id(self, subscription_id):
        """Sets the subscription_id of this AzureClientSecretCredentialFields.


        :param subscription_id: The subscription_id of this AzureClientSecretCredentialFields.  # noqa: E501
        :type: str
        """

        self._subscription_id = subscription_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            elif value is not None:
                result[attr] = value
        if issubclass(AzureClientSecretCredentialFields, dict):
            for key, value in self.items():
                if value is not None:
                    result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AzureClientSecretCredentialFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
