# coding: utf-8

"""
    Rumble API

    Rumble Network Discovery API  # noqa: E501

    OpenAPI spec version: 2.11.0
    Contact: support@rumble.run
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VMwareCredentialFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'password': 'str',
        'insecure': 'str',
        'thumbprints': 'str'
    }

    attribute_map = {
        'username': 'username',
        'password': 'password',
        'insecure': 'insecure',
        'thumbprints': 'thumbprints'
    }

    def __init__(self, username:str=None, password:str=None, insecure:str=None, thumbprints:str=None):  # noqa: E501
        """VMwareCredentialFields - a model defined in Swagger"""  # noqa: E501
        self._username = None
        self._password = None
        self._insecure = None
        self._thumbprints = None
        self.discriminator = None
        self.username = username
        self.password = password
        if insecure is not None:
            self.insecure = insecure
        if thumbprints is not None:
            self.thumbprints = thumbprints

    @property
    def username(self):
        """Gets the username of this VMwareCredentialFields.  # noqa: E501


        :return: The username of this VMwareCredentialFields.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this VMwareCredentialFields.


        :param username: The username of this VMwareCredentialFields.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this VMwareCredentialFields.  # noqa: E501


        :return: The password of this VMwareCredentialFields.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this VMwareCredentialFields.


        :param password: The password of this VMwareCredentialFields.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def insecure(self):
        """Gets the insecure of this VMwareCredentialFields.  # noqa: E501


        :return: The insecure of this VMwareCredentialFields.  # noqa: E501
        :rtype: str
        """
        return self._insecure

    @insecure.setter
    def insecure(self, insecure):
        """Sets the insecure of this VMwareCredentialFields.


        :param insecure: The insecure of this VMwareCredentialFields.  # noqa: E501
        :type: str
        """

        self._insecure = insecure

    @property
    def thumbprints(self):
        """Gets the thumbprints of this VMwareCredentialFields.  # noqa: E501


        :return: The thumbprints of this VMwareCredentialFields.  # noqa: E501
        :rtype: str
        """
        return self._thumbprints

    @thumbprints.setter
    def thumbprints(self, thumbprints):
        """Sets the thumbprints of this VMwareCredentialFields.


        :param thumbprints: The thumbprints of this VMwareCredentialFields.  # noqa: E501
        :type: str
        """

        self._thumbprints = thumbprints

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            elif value is not None:
                result[attr] = value
        if issubclass(VMwareCredentialFields, dict):
            for key, value in self.items():
                if value is not None:
                    result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VMwareCredentialFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
